baseURL: "https://followyourcode.pl"
theme: "up-business-theme"
languageCode: "pl-pl"

title: "Follow your code"

googleAnalytics: "G-0C39W1LPML"
enableRobotsTXT: true
summaryLength: 20

params:
  title: "Follow your code - Odkryj pasjonujący świat programowania"
  description: "Naszą misją jest odkrywanie przed dziećmi świata pełnego komputerów, programowania oraz robotów."
  images: 
    - "images/rocket.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "https://www.instagram.com/followyourcode.pl/"
    # facebook: "#"

  location:
    - "Podkarpackie, Polska"

  contact:
    - "followyourcode@gmail.com"

  copyright: "© 2023 Follow Your Code | Theme by Write-Only Hugo and Abell Vo"

  postProcess: false

menus:
  main:
    - name: "Aktualności"
      url: "/blog"
      weight: 2
    - name: "Kontakt"
      url: "/kontakt"
      weight: 2

  # buttons:
  #   - name: "Zgłoszenie"
  #     url: "/formularz.html"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Aktualności"
      url: "/blog"
      weight: 5

    - name: "Polityka prywatności"
      url: "/polityka-prywatnosci"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true